""" This file defines overlays to the standard vtypes.

Standard vtypes are usually autogenerated by scanning through header
files, collecting debugging symbol data etc. This file defines fixups
and improvements to the standard types.
"""

xpsp2overlays = {
    '_EPROCESS' : [ None, { \
    'CreateTime' : [ None, ['WinTimeStamp', {}]], 
    'InheritedFromUniqueProcessId' : [ None, ['unsigned int']],
    'ImageFileName' : [ None, ['String', dict(length=16)]],
    'UniqueProcessId' : [ None, ['unsigned int']], \
    }],

    '_KUSER_SHARED_DATA' : [ None, { \
    'SystemTime' : [ None, ['WinTimeStamp', {}]], \
    'TimeZoneBias' : [ None, ['WinTimeStamp', {}]], \
    }],

    '_ADDRESS_OBJECT' : [ None, { \
    'LocalPort': [ None, ['unsigned be short']], \
    'CreateTime' : [ None, ['WinTimeStamp', {}]], \
    }],

    '_OBJECT_HEADER' : [ None, {
    'Body' : [ None, ['unsigned int']],
    }],

    '_KDDEBUGGER_DATA64' : [ None, { 
    'PsActiveProcessHead' : [ None, ['pointer', ['unsigned long']]], \
    }],
    
    '_DBGKD_GET_VERSION64' : [  None, {
    'DebuggerDataList' : [ None, ['pointer', ['unsigned long']]], \
    }],
    
    '_DMP_HEADER' : [ None, {
    'PsActiveProcessHead' : [ None, ['pointer' ,['unsigned long']]], \
    }],

    '_CM_KEY_NODE' : [ None, {
    'Signature' : [ None, ['String', dict(length=2)]],
    'LastWriteTime' : [ None, ['WinTimeStamp', {}]],
    'Name' : [ None, ['String', dict(length=lambda x: x.NameLength)]],
    }],

    '_CHILD_LIST' : [ None, {
    'List' : [ None, ['pointer', ['array', lambda x: x.Count,
                                 ['pointer', ['_CM_KEY_VALUE']]]]],
    }],

    '_CM_KEY_VALUE' : [ None, {
    'Signature' : [ None, ['String', dict(length=2)]],
    'Name' : [ None, ['String', dict(length=lambda x: x.NameLength)]],
    } ],

    '_CM_KEY_INDEX' : [ None, {
    'Signature' : [ None, ['String', dict(length=2)]],
    'List' : [ None, ['array', lambda x: x.Count.v() * 2, ['pointer', ['_CM_KEY_NODE']]]],
    } ],
    
    '_IMAGE_HIBER_HEADER' : [ None, { \
    'Signature':   [ None, ['String', dict(length=4)]],
    'SystemTime' : [ None, ['WinTimeStamp', {}]], \
    } ], \

    '_PHYSICAL_MEMORY_DESCRIPTOR' : [ None, { \
    'Run' : [ None, ['array', lambda x: x.NumberOfRuns, ['_PHYSICAL_MEMORY_RUN']]], \
    } ], \

    ## This is different between Windows 2000 and WinXP. This overlay
    ## is for xp.
    '_POOL_HEADER' : [ None, { \
    'PoolIndex': [ 0x0, ['BitField', dict(start_bit = 9, end_bit = 16)]], 
    'BlockSize': [ 0x2, ['BitField', dict(start_bit = 0, end_bit = 9)]], 
    'PoolType': [ 0x2, [ 'BitField', dict(start_bit = 9, end_bit = 16)]],
    } ],\

    '_TCPT_OBJECT': [ None, {
    'RemotePort': [ None, [ 'unsigned be short']],
    'LocalPort': [ None, [ 'unsigned be short']],
    } ],

    }
